// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import "./globals.css";
import './style.css'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: {
    default: "SAATHisoft",
    template: "%s | SAATHisoft",
  },
  description: "Saathisoft Pvt. Ltd.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <link rel="icon" href="/logo.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="SAATHisoft - Where your every digital need finds its perfect solution, all in one
            place."
        />
        <meta
          name="keywords"
          content="best IT software company in pokhara, top software company, best digital company, marketing company it pokhara"
        />
        <meta property="og:title" content="SAATHisoft | Pokhara" />
        <meta property="og:description" content="Your digital partner." />
        <meta property="og:image" content="/path/to/og-image.jpg" />
        <meta property="og:url" content="https://your-website.com" />

        <link rel="canonical" href="https://www.saathisoft.com.np" />
      </head>
      <body
        className={`${inter.className} 
         bg-gradient-to-b from-[var(--background-start-color)] to-[var(--background-end-color)] box-border max-w-[1980px] mx-auto `}
      >
        <header className="w-full sticky top-0 z-[1000]">
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>

 
    </html>
  );
}
